[tool.black]
target_version = ['py36', 'py37', 'py38', 'py39']
include = '\.pyi?$'

exclude = '''
/(
    \.git
  | \.tox
  | \.venv
)/
'''
preview = true
skip_magic_trailing_comma = true

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
